# Use the Node.js Alpine image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Expose the port defined by the environment variable
EXPOSE ${AUTH_SERVICE_PORT}

# Start the application using pnpm
CMD ["pnpm", "start"]
